# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RefreshDataBasePopButton.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RefreshDataBasePopButton(object):
    def setupUi(self, RefreshDataBasePopButton):
        RefreshDataBasePopButton.setObjectName("RefreshDataBasePopButton")
        RefreshDataBasePopButton.resize(683, 305)
        self.layoutWidget = QtWidgets.QWidget(RefreshDataBasePopButton)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 271, 19))
        self.layoutWidget.setObjectName("layoutWidget")
        self.visitors_question = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.visitors_question.setContentsMargins(0, 0, 0, 0)
        self.visitors_question.setObjectName("visitors_question")
        self.question_1 = QtWidgets.QLabel(self.layoutWidget)
        self.question_1.setObjectName("question_1")
        self.visitors_question.addWidget(self.question_1)
        self.question_1_pos_ans = QtWidgets.QRadioButton(self.layoutWidget)
        self.question_1_pos_ans.setObjectName("question_1_pos_ans")
        self.visitors_question.addWidget(self.question_1_pos_ans)
        self.question_1_neg_ans = QtWidgets.QRadioButton(self.layoutWidget)
        self.question_1_neg_ans.setObjectName("question_1_neg_ans")
        self.visitors_question.addWidget(self.question_1_neg_ans)
        self.pathwaysanswer = QtWidgets.QSplitter(RefreshDataBasePopButton)
        self.pathwaysanswer.setGeometry(QtCore.QRect(40, 170, 611, 71))
        self.pathwaysanswer.setOrientation(QtCore.Qt.Vertical)
        self.pathwaysanswer.setObjectName("pathwaysanswer")
        self.xlsx_route_label = QtWidgets.QLabel(self.pathwaysanswer)
        self.xlsx_route_label.setObjectName("xlsx_route_label")
        self.xlsx_route_response_label = QtWidgets.QLabel(self.pathwaysanswer)
        self.xlsx_route_response_label.setText("")
        self.xlsx_route_response_label.setObjectName("xlsx_route_response_label")
        self.route_destiny_label = QtWidgets.QLabel(self.pathwaysanswer)
        self.route_destiny_label.setObjectName("route_destiny_label")
        self.route_destiny_response_label = QtWidgets.QLabel(self.pathwaysanswer)
        self.route_destiny_response_label.setText("")
        self.route_destiny_response_label.setObjectName("route_destiny_response_label")
        self.layoutWidget1 = QtWidgets.QWidget(RefreshDataBasePopButton)
        self.layoutWidget1.setGeometry(QtCore.QRect(270, 250, 158, 25))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.execute_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.execute_button.setObjectName("execute_button")
        self.horizontalLayout.addWidget(self.execute_button)
        self.exitbutton = QtWidgets.QPushButton(self.layoutWidget1)
        self.exitbutton.setObjectName("exitbutton")
        self.horizontalLayout.addWidget(self.exitbutton)
        self.widget = QtWidgets.QWidget(RefreshDataBasePopButton)
        self.widget.setGeometry(QtCore.QRect(30, 52, 401, 101))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.GitHub_user = QtWidgets.QLabel(self.widget)
        self.GitHub_user.setObjectName("GitHub_user")
        self.gridLayout.addWidget(self.GitHub_user, 0, 0, 1, 1)
        self.GitHub_user_ans = QtWidgets.QLineEdit(self.widget)
        self.GitHub_user_ans.setObjectName("GitHub_user_ans")
        self.gridLayout.addWidget(self.GitHub_user_ans, 0, 1, 1, 1)
        self.GitHub_repository = QtWidgets.QLabel(self.widget)
        self.GitHub_repository.setObjectName("GitHub_repository")
        self.gridLayout.addWidget(self.GitHub_repository, 1, 0, 1, 1)
        self.GitHub_repository_ans = QtWidgets.QLineEdit(self.widget)
        self.GitHub_repository_ans.setObjectName("GitHub_repository_ans")
        self.gridLayout.addWidget(self.GitHub_repository_ans, 1, 1, 1, 1)
        self.Firebase_domain = QtWidgets.QLabel(self.widget)
        self.Firebase_domain.setObjectName("Firebase_domain")
        self.gridLayout.addWidget(self.Firebase_domain, 2, 0, 1, 1)
        self.Firebase_domain_ans = QtWidgets.QLineEdit(self.widget)
        self.Firebase_domain_ans.setObjectName("Firebase_domain_ans")
        self.gridLayout.addWidget(self.Firebase_domain_ans, 2, 1, 1, 1)
        self.Firebase_key = QtWidgets.QLabel(self.widget)
        self.Firebase_key.setObjectName("Firebase_key")
        self.gridLayout.addWidget(self.Firebase_key, 3, 0, 1, 1)
        self.Firebase_key_ans = QtWidgets.QLineEdit(self.widget)
        self.Firebase_key_ans.setObjectName("Firebase_key_ans")
        self.gridLayout.addWidget(self.Firebase_key_ans, 3, 1, 1, 1)

        self.retranslateUi(RefreshDataBasePopButton)
        QtCore.QMetaObject.connectSlotsByName(RefreshDataBasePopButton)

    def retranslateUi(self, RefreshDataBasePopButton):
        _translate = QtCore.QCoreApplication.translate
        RefreshDataBasePopButton.setWindowTitle(_translate("RefreshDataBasePopButton", "Form"))
        self.question_1.setText(_translate("RefreshDataBasePopButton", "¿Deseas crear archivos para visitantes?"))
        self.question_1_pos_ans.setText(_translate("RefreshDataBasePopButton", "Si"))
        self.question_1_neg_ans.setText(_translate("RefreshDataBasePopButton", "No"))
        self.xlsx_route_label.setText(_translate("RefreshDataBasePopButton", "Ruta archivo original:"))
        self.route_destiny_label.setText(_translate("RefreshDataBasePopButton", "Ruta destino:"))
        self.execute_button.setText(_translate("RefreshDataBasePopButton", "Refrescar!"))
        self.exitbutton.setText(_translate("RefreshDataBasePopButton", "Salir"))
        self.GitHub_user.setText(_translate("RefreshDataBasePopButton", "Usuario de GitHub"))
        self.GitHub_repository.setText(_translate("RefreshDataBasePopButton", "Repositorio en GitHub"))
        self.Firebase_domain.setText(_translate("RefreshDataBasePopButton", "Dominio en Firebase"))
        self.Firebase_key.setText(_translate("RefreshDataBasePopButton", "Clave en Firesabe"))
